/**
 * Canonical test names recognised by the CCS order system.
 * Turnaround times reflect real-world stat performance at a Level I academic centre.
 * POC = point-of-care (bedside); send-out labs have multi-hour/day delays.
 */
export const TURNAROUND: Record<string, { stat: number; routine: number }> = {
  // ── Point-of-care (bedside, results in minutes) ────────────────────────────
  "Blood Glucose":          { stat:  2, routine:  5 },
  "iStat Panel":            { stat:  5, routine:  5 },  // Na/K/Cl/bicarb/BUN/Cr/glucose/Hct
  "ABG":                    { stat:  5, routine: 15 },
  "VBG":                    { stat:  5, routine: 15 },
  "Blood Gas":              { stat:  5, routine: 15 },
  "FAST Exam":              { stat:  5, routine:  5 },
  "ECG":                    { stat:  5, routine: 10 },
  "ECG (12-Lead)":          { stat:  5, routine: 10 },
  "Bedside Echo":           { stat: 10, routine: 20 },

  // ── Common stat labs (15–30 min) ───────────────────────────────────────────
  "CBC":                    { stat: 15, routine: 45 },
  "BMP":                    { stat: 15, routine: 45 },
  "Potassium":              { stat: 10, routine: 30 },
  "Sodium":                 { stat: 10, routine: 30 },
  "Creatinine":             { stat: 15, routine: 45 },
  "BUN":                    { stat: 15, routine: 45 },
  "Magnesium":              { stat: 15, routine: 45 },
  "Calcium":                { stat: 15, routine: 45 },
  "Phosphate":              { stat: 15, routine: 45 },
  "Lactate":                { stat: 10, routine: 25 },
  "Coagulation Panel":      { stat: 20, routine: 60 },
  "D-Dimer":                { stat: 20, routine: 45 },
  "Urinalysis":             { stat: 15, routine: 30 },
  "CMP":                    { stat: 20, routine: 60 },
  "LFTs":                   { stat: 20, routine: 60 },
  "Lipase":                 { stat: 20, routine: 60 },
  "Troponin":               { stat: 20, routine: 60 },
  "BNP":                    { stat: 20, routine: 60 },
  "Procalcitonin":          { stat: 25, routine: 60 },
  "CRP":                    { stat: 20, routine: 60 },
  "LDH":                    { stat: 20, routine: 60 },
  "Creatine Kinase":        { stat: 20, routine: 60 },
  "Ammonia":                { stat: 20, routine: 60 },
  "Fibrinogen":             { stat: 20, routine: 60 },
  "Fibrin Split Products":  { stat: 20, routine: 45 },
  "Uric Acid":              { stat: 20, routine: 60 },
  "Albumin":                { stat: 20, routine: 60 },
  "Bilirubin":              { stat: 20, routine: 60 },
  "Reticulocyte Count":     { stat: 20, routine: 60 },
  "Haptoglobin":            { stat: 25, routine: 60 },
  "Direct Coombs":          { stat: 30, routine: 60 },
  "Type and Screen":        { stat: 30, routine: 60 },
  "Crossmatch":             { stat: 45, routine: 90 },
  "Drug Screen":            { stat: 30, routine: 90 },
  "TSH":                    { stat: 30, routine: 90 },
  "Free T4":                { stat: 30, routine: 90 },
  "HbA1c":                  { stat: 30, routine: 90 },
  "Ferritin":               { stat: 30, routine: 90 },
  "Iron Studies":           { stat: 30, routine: 90 },
  "ESR":                    { stat: 45, routine: 90 },
  "Cortisol":               { stat: 45, routine: 90 },
  "PTH":                    { stat: 60, routine: 120 },
  "HIV Test":               { stat: 60, routine: 120 },
  "Hepatitis Panel":        { stat: 60, routine: 180 },
  "Peripheral Smear":       { stat: 60, routine: 120 },
  "Sickle Cell Screen":     { stat: 60, routine: 120 },
  "G6PD":                   { stat: 120, routine: 240 },
  "Antithrombin III":       { stat: 120, routine: 240 },
  "Urine Electrolytes":     { stat: 30, routine: 60 },
  "Urine Osmolality":       { stat: 30, routine: 60 },
  "Urine Protein/Cr Ratio": { stat: 30, routine: 60 },
  "Urine Culture":          { stat: 120, routine: 1440 },
  "Blood Culture":          { stat: 2880, routine: 4320 }, // 48–72 hrs for first positivity signal

  // ── Specialist / send-out labs (hours to days) ────────────────────────────
  "Vitamin B12":            { stat: 120, routine: 240 },
  "Folate":                 { stat: 120, routine: 240 },
  "Vitamin D":              { stat: 240, routine: 480 },
  "Thyroid Panel":          { stat: 60, routine: 180 },
  "Cortisol Stimulation Test": { stat: 60, routine: 120 },
  "ANA":                    { stat: 240, routine: 1440 },
  "Anti-dsDNA":             { stat: 480, routine: 2880 },
  "Complement C3/C4":       { stat: 240, routine: 480 },
  "Complement CH50":        { stat: 240, routine: 480 },
  "ANCA":                   { stat: 480, routine: 2880 },
  "Anti-GBM Antibody":      { stat: 720, routine: 4320 },
  "ADAMTS13 Activity":      { stat: 1440, routine: 4320 },
  "Anti-Phospholipid Panel":{ stat: 1440, routine: 4320 },
  "Cryoglobulins":          { stat: 2880, routine: 4320 },
  "Serum Protein Electrophoresis": { stat: 240, routine: 720 },
  "Immunofixation":         { stat: 480, routine: 1440 },
  "Free Light Chains":      { stat: 240, routine: 480 },
  "HIV Viral Load":         { stat: 480, routine: 1440 },
  "CMV PCR":                { stat: 480, routine: 1440 },
  "EBV PCR":                { stat: 480, routine: 1440 },
  "Beta-Glucan":            { stat: 480, routine: 1440 },
  "Galactomannan":          { stat: 480, routine: 1440 },
  "PTHrP":                  { stat: 480, routine: 1440 },
  "Calcitonin":             { stat: 480, routine: 1440 },
  "Chromogranin A":         { stat: 480, routine: 1440 },
  "24h Urine Protein":      { stat: 1440, routine: 1440 },
  "Hemoglobin Electrophoresis": { stat: 240, routine: 720 },
  "Factor VIII Assay":      { stat: 240, routine: 720 },
  "Von Willebrand Factor":  { stat: 240, routine: 720 },
  "Protein C":              { stat: 240, routine: 720 },
  "Protein S":              { stat: 240, routine: 720 },
  "Factor V Leiden":        { stat: 1440, routine: 4320 },
  "Prothrombin Gene Mutation": { stat: 1440, routine: 4320 },
  "Confirmatory Drug Screen": { stat: 4320, routine: 4320 }, // GC/MS

  // ── Imaging (scan + radiology prelim read) ────────────────────────────────
  "Chest X-ray":            { stat: 20, routine: 45 },
  "X-ray":                  { stat: 15, routine: 45 },
  "FAST Exam":              { stat:  5, routine:  5 },
  "Ultrasound":             { stat: 25, routine: 60 },
  "Renal Ultrasound":       { stat: 30, routine: 60 },
  "Abdominal Ultrasound":   { stat: 30, routine: 60 },
  "Pelvic Ultrasound":      { stat: 30, routine: 60 },
  "Liver Ultrasound":       { stat: 30, routine: 60 },
  "DVT Ultrasound":         { stat: 45, routine: 90 },
  "Carotid Doppler":        { stat: 60, routine: 120 },
  "Echocardiogram":         { stat: 45, routine: 90 },
  "Transesophageal Echo":   { stat: 60, routine: 120 },
  "CT Head":                { stat: 35, routine: 75 },
  "CT Chest":               { stat: 35, routine: 75 },
  "CT Abdomen/Pelvis":      { stat: 40, routine: 90 },
  "CT PE Protocol":         { stat: 35, routine: 75 },
  "CT Angiogram":           { stat: 40, routine: 90 },
  "CT Spine":               { stat: 40, routine: 90 },
  "CT Neck":                { stat: 35, routine: 75 },
  "CT with Contrast":       { stat: 40, routine: 90 },
  "CTA Head/Neck":          { stat: 40, routine: 90 },
  "MRI Brain":              { stat: 75, routine: 120 },
  "MRI Spine":              { stat: 90, routine: 150 },
  "MRI Cardiac":            { stat: 120, routine: 240 },
  "MRI Abdomen":            { stat: 120, routine: 240 },
  "V/Q Scan":               { stat: 120, routine: 240 },
  "Nuclear Medicine":       { stat: 240, routine: 480 },
  "Bone Scan":              { stat: 300, routine: 480 },
  "PET Scan":               { stat: 180, routine: 480 },
  "Interventional Angio":   { stat: 90, routine: 240 },
  "Lumbar Puncture":        { stat: 30, routine: 30 },  // procedure time; CSF culture = 4320
  "CSF Culture":            { stat: 2880, routine: 4320 },
  "Paracentesis":           { stat: 30, routine: 30 },
  "Thoracentesis":          { stat: 30, routine: 30 },
};

/**
 * Explicit alias map: every AI/user variant → canonical TURNAROUND key.
 */
export const ALIASES: Record<string, string> = {
  // Troponin
  "troponin i":                    "Troponin",
  "troponin t":                    "Troponin",
  "trop i":                        "Troponin",
  "trop t":                        "Troponin",
  "high-sensitivity troponin":     "Troponin",
  "hs-troponin":                   "Troponin",
  "hs troponin":                   "Troponin",
  "cardiac troponin":              "Troponin",
  "hstni":                         "Troponin",
  "serial troponin":               "Troponin",
  // BMP / CMP
  "basic metabolic panel":         "BMP",
  "comprehensive metabolic panel": "CMP",
  "comprehensive metabolic":       "CMP",
  "chem 7":                        "BMP",
  "chem7":                         "BMP",
  "chem 8":                        "BMP",
  // CBC
  "complete blood count":          "CBC",
  "complete blood cell count":     "CBC",
  "full blood count":              "CBC",
  "fbc":                           "CBC",
  // Coagulation
  "coagulation":                   "Coagulation Panel",
  "pt/inr":                        "Coagulation Panel",
  "pt inr":                        "Coagulation Panel",
  "inr":                           "Coagulation Panel",
  "ptt":                           "Coagulation Panel",
  "aptt":                          "Coagulation Panel",
  "prothrombin":                   "Coagulation Panel",
  "coags":                         "Coagulation Panel",
  "clotting screen":               "Coagulation Panel",
  // LFTs
  "liver function":                "LFTs",
  "liver function tests":          "LFTs",
  "hepatic function":              "LFTs",
  "liver panel":                   "LFTs",
  "ast/alt":                       "LFTs",
  // BNP
  "nt-probnp":                     "BNP",
  "nt probnp":                     "BNP",
  "pro-bnp":                       "BNP",
  "brain natriuretic peptide":     "BNP",
  "nt-pro-bnp":                    "BNP",
  // ABG / Blood Gas
  "arterial blood gas":            "ABG",
  "blood gas":                     "ABG",
  // VBG
  "venous blood gas":              "VBG",
  // Lactate
  "lactic acid":                   "Lactate",
  "serum lactate":                 "Lactate",
  "blood lactate":                 "Lactate",
  // Urinalysis
  "ua":                            "Urinalysis",
  "urine analysis":                "Urinalysis",
  "urine dipstick":                "Urinalysis",
  // D-Dimer
  "d dimer":                       "D-Dimer",
  // Drug screen
  "toxicology screen":             "Drug Screen",
  "urine drug screen":             "Drug Screen",
  "uds":                           "Drug Screen",
  "tox screen":                    "Drug Screen",
  "serum tox":                     "Drug Screen",
  "acetaminophen level":           "Drug Screen",
  "salicylate level":              "Drug Screen",
  "ethanol level":                 "Drug Screen",
  // ECG
  "ekg":                           "ECG",
  "electrocardiogram":             "ECG",
  "12-lead ecg":                   "ECG (12-Lead)",
  "12 lead ecg":                   "ECG (12-Lead)",
  "12 lead ekg":                   "ECG (12-Lead)",
  "12-lead ekg":                   "ECG (12-Lead)",
  "12-lead":                       "ECG (12-Lead)",
  "ecg 12 lead":                   "ECG (12-Lead)",
  "ecg (12-lead)":                 "ECG (12-Lead)",
  // Chest X-ray
  "cxr":                           "Chest X-ray",
  "chest x ray":                   "Chest X-ray",
  "chest xray":                    "Chest X-ray",
  "chest radiograph":              "Chest X-ray",
  "chest pa":                      "Chest X-ray",
  "portable cxr":                  "Chest X-ray",
  "ap cxr":                        "Chest X-ray",
  // CT Head — all explicit, no fuzzy fallback
  "ct head":                       "CT Head",
  "ct scan head":                  "CT Head",
  "ct brain":                      "CT Head",
  "ct of head":                    "CT Head",
  "ct of the head":                "CT Head",
  "ct non-contrast head":          "CT Head",
  "ct head without contrast":      "CT Head",
  "ct head with contrast":         "CT Head",
  "ct scan of head":               "CT Head",
  "non-contrast ct head":          "CT Head",
  "nchct":                         "CT Head",
  // CT Chest
  "ct chest":                      "CT Chest",
  "ct scan chest":                 "CT Chest",
  "ct of chest":                   "CT Chest",
  "ct of the chest":               "CT Chest",
  "ct chest without contrast":     "CT Chest",
  "ct chest with contrast":        "CT Chest",
  "ct scan of chest":              "CT Chest",
  "ct thorax":                     "CT Chest",
  // CT PE Protocol
  "ct pulmonary angiography":      "CT PE Protocol",
  "ctpa":                          "CT PE Protocol",
  "ct angiography chest":          "CT PE Protocol",
  "ct pulmonary embolism":         "CT PE Protocol",
  "ct pe":                         "CT PE Protocol",
  "pulmonary cta":                 "CT PE Protocol",
  // CT Abdomen/Pelvis
  "ct abdomen/pelvis":             "CT Abdomen/Pelvis",
  "ct abdomen":                    "CT Abdomen/Pelvis",
  "ct pelvis":                     "CT Abdomen/Pelvis",
  "ct ab/pelvis":                  "CT Abdomen/Pelvis",
  "ct abdomen and pelvis":         "CT Abdomen/Pelvis",
  "ct of abdomen":                 "CT Abdomen/Pelvis",
  "ct of abdomen and pelvis":      "CT Abdomen/Pelvis",
  "ct scan abdomen":               "CT Abdomen/Pelvis",
  "ct scan abdomen and pelvis":    "CT Abdomen/Pelvis",
  "ct abdomen pelvis":             "CT Abdomen/Pelvis",
  // Echocardiogram
  "echo":                          "Echocardiogram",
  "cardiac echo":                  "Echocardiogram",
  "transthoracic echo":            "Echocardiogram",
  "tte":                           "Echocardiogram",
  "transthoracic echocardiogram":  "Echocardiogram",
  // Transesophageal Echo
  "tee":                           "Transesophageal Echo",
  "transesophageal echocardiogram":"Transesophageal Echo",
  "transoesophageal echo":         "Transesophageal Echo",
  // MRI Brain
  "mri head":                      "MRI Brain",
  "mri of the brain":              "MRI Brain",
  "mri brain with contrast":       "MRI Brain",
  "mri brain without contrast":    "MRI Brain",
  "mri dwi":                       "MRI Brain",
  "diffusion mri":                 "MRI Brain",
  // MRI Spine
  "mri c-spine":                   "MRI Spine",
  "mri cervical spine":            "MRI Spine",
  "mri lumbar spine":              "MRI Spine",
  "mri l-spine":                   "MRI Spine",
  "mri thoracic spine":            "MRI Spine",
  // Ultrasound
  "us":                            "Ultrasound",
  "bedside us":                    "Ultrasound",
  "point of care ultrasound":      "Ultrasound",
  "pocus":                         "Ultrasound",
  "renal ultrasound":              "Renal Ultrasound",
  "abdominal ultrasound":          "Abdominal Ultrasound",
  "abdominal us":                  "Abdominal Ultrasound",
  "liver ultrasound":              "Liver Ultrasound",
  "ruq ultrasound":                "Liver Ultrasound",
  "ruq us":                        "Liver Ultrasound",
  "dvt ultrasound":                "DVT Ultrasound",
  "lower extremity doppler":       "DVT Ultrasound",
  "le doppler":                    "DVT Ultrasound",
  "venous doppler":                "DVT Ultrasound",
  "pelvic us":                     "Pelvic Ultrasound",
  "pelvic ultrasound":             "Pelvic Ultrasound",
  "transvaginal us":               "Pelvic Ultrasound",
  "carotid ultrasound":            "Carotid Doppler",
  "carotid doppler":               "Carotid Doppler",
  // Blood culture
  "blood cultures":                "Blood Culture",
  "2x blood cultures":             "Blood Culture",
  "bc":                            "Blood Culture",
  // Blood Glucose
  "glucose":                       "Blood Glucose",
  "bgl":                           "Blood Glucose",
  "blood sugar":                   "Blood Glucose",
  "finger stick":                  "Blood Glucose",
  "fingerstick glucose":           "Blood Glucose",
  "point of care glucose":         "Blood Glucose",
  "cbg":                           "Blood Glucose",
  // CRP
  "c-reactive protein":            "CRP",
  "c reactive protein":            "CRP",
  "high-sensitivity crp":          "CRP",
  "hscrp":                         "CRP",
  // Magnesium
  "mag":                           "Magnesium",
  "mg level":                      "Magnesium",
  "serum magnesium":               "Magnesium",
  // Calcium
  "ca level":                      "Calcium",
  "serum calcium":                 "Calcium",
  "ionized calcium":               "Calcium",
  "corrected calcium":             "Calcium",
  // Potassium
  "k level":                       "Potassium",
  "serum potassium":               "Potassium",
  // Creatinine
  "creat":                         "Creatinine",
  "serum creatinine":              "Creatinine",
  "scr":                           "Creatinine",
  // CK
  "ck":                            "Creatine Kinase",
  "cpk":                           "Creatine Kinase",
  "creatine phosphokinase":        "Creatine Kinase",
  "ck-mb":                         "Creatine Kinase",
  // Type and screen
  "type and cross":                "Type and Screen",
  "crossmatch":                    "Crossmatch",
  "blood bank":                    "Type and Screen",
  "t&s":                           "Type and Screen",
  // Iron
  "iron":                          "Iron Studies",
  "iron panel":                    "Iron Studies",
  "serum iron":                    "Iron Studies",
  "tibc":                          "Iron Studies",
  // LDH
  "lactate dehydrogenase":         "LDH",
  // Ammonia
  "serum ammonia":                 "Ammonia",
  "nh3":                           "Ammonia",
  // Cortisol
  "random cortisol":               "Cortisol",
  "am cortisol":                   "Cortisol",
  "serum cortisol":                "Cortisol",
  // Thyroid
  "thyroid function":              "Thyroid Panel",
  "tfts":                          "Thyroid Panel",
  "free thyroxine":                "Free T4",
  "ft4":                           "Free T4",
  "t3":                            "Thyroid Panel",
  "t4":                            "Free T4",
  "thyroid stimulating hormone":   "TSH",
  // ANA / autoimmune
  "antinuclear antibody":          "ANA",
  "ana screen":                    "ANA",
  "anti-double stranded dna":      "Anti-dsDNA",
  "anti ds-dna":                   "Anti-dsDNA",
  "anti dsdna":                    "Anti-dsDNA",
  "antineutrophil cytoplasmic":    "ANCA",
  "c-anca":                        "ANCA",
  "p-anca":                        "ANCA",
  "pr3/mpo":                       "ANCA",
  "anti-gbm":                      "Anti-GBM Antibody",
  "anti gbm":                      "Anti-GBM Antibody",
  "goodpasture":                   "Anti-GBM Antibody",
  "complement":                    "Complement C3/C4",
  "c3":                            "Complement C3/C4",
  "c4":                            "Complement C3/C4",
  "c3/c4":                         "Complement C3/C4",
  "ch50":                          "Complement CH50",
  // Haematology
  "peripheral blood smear":        "Peripheral Smear",
  "blood film":                    "Peripheral Smear",
  "blood smear":                   "Peripheral Smear",
  "direct antiglobulin test":      "Direct Coombs",
  "dat":                           "Direct Coombs",
  "hb electrophoresis":            "Hemoglobin Electrophoresis",
  "sickle prep":                   "Sickle Cell Screen",
  "sickling test":                 "Sickle Cell Screen",
  "reticulocytes":                 "Reticulocyte Count",
  "retic count":                   "Reticulocyte Count",
  // Immunology / Oncology
  "serum protein electro":         "Serum Protein Electrophoresis",
  "spep":                          "Serum Protein Electrophoresis",
  "upep":                          "Serum Protein Electrophoresis",
  "protein electrophoresis":       "Serum Protein Electrophoresis",
  "free kappa lambda":             "Free Light Chains",
  "serum free light chains":       "Free Light Chains",
  "adamts 13":                     "ADAMTS13 Activity",
  "adamts-13":                     "ADAMTS13 Activity",
  "anti-phospholipid":             "Anti-Phospholipid Panel",
  "apla":                          "Anti-Phospholipid Panel",
  "lupus anticoagulant":           "Anti-Phospholipid Panel",
  "anticardiolipin":               "Anti-Phospholipid Panel",
  "beta-2 glycoprotein":           "Anti-Phospholipid Panel",
  // Infectious
  "hiv":                           "HIV Test",
  "hiv rapid":                     "HIV Test",
  "4th gen hiv":                   "HIV Test",
  "hep panel":                     "Hepatitis Panel",
  "hepatitis b":                   "Hepatitis Panel",
  "hepatitis c":                   "Hepatitis Panel",
  "hbsag":                         "Hepatitis Panel",
  "hcv":                           "Hepatitis Panel",
  "cmv":                           "CMV PCR",
  "ebv":                           "EBV PCR",
  "beta glucan":                   "Beta-Glucan",
  "fungitell":                     "Beta-Glucan",
  "galacto":                       "Galactomannan",
  // Endocrine / Metabolic
  "parathyroid hormone":           "PTH",
  "ipth":                          "PTH",
  "intact pth":                    "PTH",
  "pth-related protein":           "PTHrP",
  "parathyroid related protein":   "PTHrP",
  "25-oh vitamin d":               "Vitamin D",
  "25 oh vitamin d":               "Vitamin D",
  "vit d":                         "Vitamin D",
  "vitamin b12":                   "Vitamin B12",
  "b12":                           "Vitamin B12",
  "cobalamin":                     "Vitamin B12",
  "folate":                        "Folate",
  "folic acid":                    "Folate",
  "haemoglobin a1c":               "HbA1c",
  "hemoglobin a1c":                "HbA1c",
  "a1c":                           "HbA1c",
  "g6pd screen":                   "G6PD",
  "glucose 6 phosphate":           "G6PD",
  // Urine
  "urine electrolytes":            "Urine Electrolytes",
  "urine na":                      "Urine Electrolytes",
  "fena":                          "Urine Electrolytes",
  "fractional excretion of sodium":"Urine Electrolytes",
  "urine osm":                     "Urine Osmolality",
  "urine osmolarity":              "Urine Osmolality",
  "spot urine protein":            "Urine Protein/Cr Ratio",
  "urine pcr":                     "Urine Protein/Cr Ratio",
  "urine protein creatinine":      "Urine Protein/Cr Ratio",
  "24h urine":                     "24h Urine Protein",
  "24 hour urine":                 "24h Urine Protein",
  "urine cultures":                "Urine Culture",
  // Imaging extras
  "fast":                          "FAST Exam",
  "fast exam":                     "FAST Exam",
  "focused assessment":            "FAST Exam",
  "vq scan":                       "V/Q Scan",
  "ventilation perfusion":         "V/Q Scan",
  "v/q":                           "V/Q Scan",
  "ct angiogram":                  "CT Angiogram",
  "cta":                           "CT Angiogram",
  "ct angio":                      "CT Angiogram",
  "cta head neck":                 "CTA Head/Neck",
  "ct spine":                      "CT Spine",
  "ct c-spine":                    "CT Spine",
  "ct cervical spine":             "CT Spine",
  "x-ray":                         "X-ray",
  "xray":                          "X-ray",
  "x ray":                         "X-ray",
  "pelvic xray":                   "X-ray",
  "ankle xray":                    "X-ray",
  "wrist xray":                    "X-ray",
  "knee xray":                     "X-ray",
  "abdominal xray":                "X-ray",
  "kub":                           "X-ray",
  "isstat":                        "iStat Panel",
  "istat":                         "iStat Panel",
  "point of care panel":           "iStat Panel",
  // Procedures
  "lp":                            "Lumbar Puncture",
  "spinal tap":                    "Lumbar Puncture",
  "csf":                           "Lumbar Puncture",
  "csf analysis":                  "Lumbar Puncture",
  "csf culture":                   "CSF Culture",
  "pleural fluid":                 "Thoracentesis",
  "thoracentesis":                 "Thoracentesis",
  "ascitic tap":                   "Paracentesis",
  "ascites tap":                   "Paracentesis",
  "abdominal paracentesis":        "Paracentesis",
};

/**
 * Normalise any test name → canonical TURNAROUND key.
 *
 * Resolution order:
 *  1. Exact case-insensitive match against TURNAROUND keys
 *  2. Exact lookup in ALIASES (covers every known variant)
 *  3. Prefix match against ALIASES entries (min length 4, skips "ct" ambiguity)
 *
 * Returns the raw string unchanged if nothing matches — caller uses DEFAULT_TURNAROUND.
 */
export function normaliseTestName(raw: string): string {
  const lower = raw.trim().toLowerCase();

  // 1. Exact match against canonical keys
  const exact = Object.keys(TURNAROUND).find(k => k.toLowerCase() === lower);
  if (exact) return exact;

  // 2. Alias lookup
  if (ALIASES[lower]) return ALIASES[lower];

  // 3. Safe prefix match against alias keys (≥ 4 chars, skip "ct" ambiguity)
  const prefixMatch = Object.entries(ALIASES).find(
    ([alias]) => alias.length >= 4 && lower.startsWith(alias)
  );
  if (prefixMatch) return prefixMatch[1];

  return raw;
}

export const DEFAULT_TURNAROUND = {
  lab:     { stat: 20, routine: 60 },
  imaging: { stat: 30, routine: 75 },
};
